# Generated by Django 5.2.17 on 2026-09-21 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_pin',
        ),
    ]
