# Generated by Django 5.2.17 on 2026-09-23 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_recipient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('money_in', 'Money in'), ('money_out', 'Money out'), ('request', 'Payment request'), ('settled', 'Settlement'), ('kyc', 'KYC')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(blank=True, max_length=400)),
                ('link', models.CharField(blank=True, max_length=300)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='account_not_user_id_42f819_idx'), models.Index(fields=['user', 'is_read'], name='account_not_user_id_87f092_idx')],
            },
        ),
    ]
