# Generated by Django 5.2.17 on 2026-09-24 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_supportticket_supportreply'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('icon', models.CharField(choices=[('cart', 'Groceries'), ('home', 'Housing'), ('car', 'Transport'), ('ticket', 'Entertainment'), ('bolt', 'Utilities'), ('dots', 'Other')], default='dots', max_length=20)),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('orange', 'Orange'), ('purple', 'Purple'), ('red', 'Red'), ('gray', 'Gray')], default='gray', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'slug'), name='unique_category_per_user')],
            },
        ),
    ]
