# Generated by Django 5.2.17 on 2026-09-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('excerpt', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('fintech', 'Fintech'), ('finance-tips', 'Finance Tips'), ('security', 'Security'), ('budgeting', 'Budgeting'), ('technology', 'Technology'), ('business', 'Business')], max_length=30)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('author_name', models.CharField(max_length=100)),
                ('cover_gradient', models.CharField(choices=[('primary-purple', 'Primary → Purple'), ('azure-blue', 'Azure → Blue'), ('teal-cyan', 'Teal → Cyan'), ('orange-red', 'Orange → Red'), ('indigo-purple', 'Indigo → Purple'), ('green-lime', 'Green → Lime')], default='primary-purple', max_length=30)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['-published_at'], name='pages_blogp_publish_5d8812_idx')],
            },
        ),
    ]
