# Generated by Django 5.2.17 on 2026-09-24 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_register', 'User registered'), ('user_login', 'User logged in'), ('user_logout', 'User logged out'), ('user_login_failed', 'Login failed'), ('kyc_submitted', 'KYC submitted'), ('settings_changed', 'Settings changed'), ('password_changed', 'Password changed'), ('transfer_created', 'Transfer created'), ('transfer_confirmed', 'Transfer confirmed'), ('transfer_failed', 'Transfer failed'), ('request_created', 'Payment request created'), ('request_sent', 'Payment request sent'), ('settlement_confirmed', 'Settlement confirmed'), ('settlement_failed', 'Settlement failed'), ('recipient_added', 'Recipient added'), ('recipient_removed', 'Recipient removed'), ('support_ticket_created', 'Support ticket created'), ('support_reply_created', 'Support reply created'), ('rate_limited', 'Rate limited')], max_length=40)),
                ('target_type', models.CharField(blank=True, max_length=40)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='audit_logen_created_908b6c_idx'), models.Index(fields=['actor', '-created_at'], name='audit_logen_actor_i_0d2d84_idx'), models.Index(fields=['action', '-created_at'], name='audit_logen_action_e26658_idx'), models.Index(fields=['target_type', 'target_id'], name='audit_logen_target__7cbecf_idx')],
            },
        ),
    ]
