# Generated by Django 5.2.17 on 2026-09-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='action',
            field=models.CharField(choices=[('user_register', 'User registered'), ('user_login', 'User logged in'), ('user_logout', 'User logged out'), ('user_login_failed', 'Login failed'), ('kyc_submitted', 'KYC submitted'), ('settings_changed', 'Settings changed'), ('password_changed', 'Password changed'), ('transfer_created', 'Transfer created'), ('transfer_confirmed', 'Transfer confirmed'), ('transfer_failed', 'Transfer failed'), ('request_created', 'Payment request created'), ('request_sent', 'Payment request sent'), ('settlement_confirmed', 'Settlement confirmed'), ('settlement_failed', 'Settlement failed'), ('recipient_added', 'Recipient added'), ('recipient_removed', 'Recipient removed'), ('support_ticket_created', 'Support ticket created'), ('support_reply_created', 'Support reply created'), ('rate_limited', 'Rate limited'), ('2fa_enabled', 'Two-factor authentication enabled'), ('2fa_disabled', 'Two-factor authentication disabled'), ('2fa_challenge_passed', 'Two-factor challenge passed'), ('2fa_challenge_failed', 'Two-factor challenge failed')], max_length=40),
        ),
    ]
